erlc cputest.erl
erlc mapredsrv.erl
erlc mapredwrk.erl
erlc mrs_api.erl
erlc mrs_db.erl
erlc mrs_jlogic.erl
erlc mrs_job.erl
erlc mrs_jtask.erl
erlc mrs_planner.erl
erlc mrs_util.erl
erlc mrs_worker.erl
erlc test1.erl
erlc test2.erl